language: python
python:
 - "3.5.4"

install:
 - pip install -r requirements.txt
 - pip install coveralls

script:
 - python -m unittest discover 
 - python3 -m pytest --cov

after_success:
 - coveralls    